### ISSUE TITLE
PO Box provisioning fails due to IMOS pgsql extension

### ISSUE THREAD

**Issue by danfruehauf** [aodn/chef#245]
See:
https://jenkins.aodn.org.au/view/chef/job/chef_cook_po_box/39/console

A snippet from the log:
```
==> po: [2016-01-27T03:36:39+11:00] INFO: [ruby_block[link-extension-main-imos]] sending create action to ruby_block[main-harvest-public-imos-custom-extension-reload-from-repo] (delayed)
==> po: Recipe: imos_postgresql::official_postgresql
==> po:   * ruby_block[main-harvest-public-imos-custom-extension-reload-from-repo] action create[2016-01-27T03:36:39+11:00] INFO: Updating custom extension 'imos' from files in schema 'public' for database 'harvest'
==> po: [2016-01-27T03:36:39+11:00] FATAL: ShellOut failed 'NOTICE:  extension "imos" does not exist, skipping
==> po: ERROR:  attempt to redefine parameter "postgis.backend"
==> po: '
==> po:     
==> po:     
==> po: ================================================================================
==> po:     
==> po: Error executing action `create` on resource 'ruby_block[main-harvest-public-imos-custom-extension-reload-from-repo]'
==> po:     
==> po: ================================================================================
==> po:     
==> po:     
==> po: SystemExit
==> po:     
==> po: ----------
==> po:     exit
==> po:     
==> po:     Cookbook Trace:
==> po:     ---------------
==> po:     /tmp/vagrant-chef/6fa2848b690ebcc70a933f08d0b8fe00/cookbooks/imos_postgresql/libraries/postgresql_helper.rb:40:in `query_basic'
==> po:     /tmp/vagrant-chef/6fa2848b690ebcc70a933f08d0b8fe00/cookbooks/imos_postgresql/definitions/imos_postgresql_database_with_schemas.rb:561:in `block (5 levels) in from_file'
==> po:     
==> po:     Resource Declaration:
==> po:     ---------------------
==> po:     # In /tmp/vagrant-chef/6fa2848b690ebcc70a933f08d0b8fe00/cookbooks/imos_postgresql/definitions/imos_postgresql_database_with_schemas.rb
==> po:     
==> po:     557:         ruby_block "#{resource_prefix}-#{extension_name}-custom-extension-reload-from-repo" do
==> po:     558:           block do
==> po:     559:             Chef::Log.info("Updating custom extension '#{extension_name}' from files in schema '#{schema_name}' for database '#{database_name}'")
==> po:     560: 
==> po:     561:             PostgresqlHelper.query_basic(port, database_name,
==> po:     562:               <<-EOS
==> po:     563:                 -- Perhaps should be using recreate extension
==> po:     564:                 drop extension if exists \\"#{extension_name}\\";
==> po:     565:                 create extension \\"#{extension_name}\\" schema #{schema_name};
==> po:     566:               EOS
==> po:     567:             )
==> po:     568:           end
==> po:     569:           action :nothing
==> po:     570:           subscribes :create, "ruby_block[link-extension-#{cluster_name}-#{extension_name}]"
==> po:     571:         end
```

**Comment by danfruehauf** [comment]
Fixed by aodn/harvest_sql_library#8
