### ISSUE TITLE
s3lsv fails to download previous version objects

### ISSUE THREAD

**Issue by lbesnard** [aodn/chef#293]
Example

```
$ s3lsv -a -b imos-data -k IMOS/SOOP/SOOP-BA/ZM7552_Kaharoa/Kaharoa_20130726-20130801/IMOS_SOOP-BA_AE_20130726T151951Z__FV02_Kaharoa-ES60-38_END-20130801T222223Z_C-20140902T231252Z.nc.png
OgjAD70L15chky5f5wV_7o0FLDtct2NA 2015-12-18T00:49:18.000Z IMOS/SOOP/SOOP-BA/ZM7552_Kaharoa/Kaharoa_20130726-20130801/IMOS_SOOP-BA_AE_20130726T151951Z__FV02_Kaharoa-ES60-38_END-20130801T222223Z_C-20140902T231252Z.nc.png
FF8mZxF2.Sbcyyar87xxBMurpjMxMOLR 2015-11-26T05:33:00.000Z IMOS/SOOP/SOOP-BA/ZM7552_Kaharoa/Kaharoa_20130726-20130801/IMOS_SOOP-BA_AE_20130726T151951Z__FV02_Kaharoa-ES60-38_END-20130801T222223Z_C-20140902T231252Z.nc.png
```

As we can see there are two versions for this file.

```
$ s3lsv -a -b imos-data -k IMOS/SOOP/SOOP-BA/ZM7552_Kaharoa/Kaharoa_20130726-20130801/IMOS_SOOP-BA_AE_20130726T151951Z__FV02_Kaharoa-ES60-38_END-20130801T222223Z_C-20140902T231252Z.nc.png -o /tmp/test.nc -v FF8mZxF2.Sbcyyar87xxBMurpjMxMOLR
# works successfully
# but the following one fails
$ s3lsv -a -b imos-data -k IMOS/SOOP/SOOP-BA/ZM7552_Kaharoa/Kaharoa_20130726-20130801/IMOS_SOOP-BA_AE_20130726T151951Z__FV02_Kaharoa-ES60-38_END-20130801T222223Z_C-20140902T231252Z.nc.png -o /tmp/test.nc -v OgjAD70L15chky5f5wV_7o0FLDtct2NA
Traceback (most recent call last):
  File "/usr/local/bin/s3lsv", line 32, in <module>
    get_object_with_version(bucket, args.key, args.version, args.output)
  File "/usr/local/bin/s3lsv", line 8, in get_object_with_version
    k = bucket.get_key(key, version_id=version)
  File "/usr/lib/python2.7/dist-packages/boto/s3/bucket.py", line 206, in get_key
    response.status, response.reason, '')
boto.exception.S3ResponseError: S3ResponseError: 405 Method Not Allowed
```

This seems to happen with files which aren't directly available on data.aodn.org.au

**Comment by pblain** [comment]
@pmbohm - please close this if it's done. Assigning it to you.
