### ISSUE TITLE
PO box provision fails on deploying aatams_sattag_dm artifact

### ISSUE THREAD

**Issue by mhidas** [aodn/chef#400]
```
==> po:     Error executing action `deploy` on resource 'imos_artifacts_deploy[aatams_sattag_dm-aatams_sattag_dm]'
==> po:     ================================================================================
==> po:     
==> po:     NoMethodError
==> po:     -------------
==> po:     undefined method `read' for nil:NilClass
==> po:     
==> po:     Cookbook Trace:
==> po:     ---------------
==> po:     /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_artifacts/libraries/fetcher_jenkins.rb:59:in `cache'
==> po:     /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_artifacts/libraries/fetcher.rb:28:in `fetch_jenkins_artifact'
==> po:     /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_artifacts/libraries/fetcher.rb:21:in `fetch_artifact'
==> po:     /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_artifacts/providers/deploy.rb:18:in `block in class_from_file'
==> po:     
==> po:     Resource Declaration:
==> po:     ---------------------
==> po:     # In /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/talend/providers/job.rb
==> po:     
==> po:     110:   imos_artifacts_deploy job_name do
==> po:     111:     install_dir                job_java_dir
==> po:     112:     artifact_id                new_resource.artifact_id
==> po:     113:     artifact_manifest          new_resource.artifact_manifest
==> po:     114:     file_destination           ::File.join(job_dir, "#{new_resource.common_name}.zip")
==> po:     115:     # Remove redundant directory structure
==> po:     116:     remove_top_level_directory true
==> po:     117:     owner                      'root'
==> po:     118:     group                      'root'
==> po:     119:   end
==> po:     120: end
```

**Comment by mhidas** [comment]
Actually I don't think there's anything special about aatams_sattag_dm, it just happens to be the first one on the talend jobs list in nodes/po.json . If I remove it, I get another error for the next talend job on the list. And just before it, there's this, which might be relevant...

```
==> po: [2016-09-21T17:52:01+10:00] FATAL: No artifacts found for 'aatams_sattag_nrt_harvester_Latest.zip' in 'talend_build' job. Check Jenkins build results for this job.
```

**Comment by lwgordonimos** [comment]
@mhidas that was the message I added to make this scenario less confusing... it can't get the artifacts from Jenkins because:

1. they aren't there in the latest build (this had happened before... due to deletion?)
2. the security is preventing non-authenticated access, which has also happened before (due to Jenkins failing to cook correctly)

Will work out which it is and fix...

**Comment by pblain** [comment]
No longer relevant
