### ISSUE TITLE
systest failed to start

### ISSUE THREAD

**Issue by julian1** [aodn/chef#481]
This probably doesn't justify an issue. But since I don't know the code or significance, it makes sense to record it.  
 

```
2017-03-23 20:48:56,354 INFO [botocore.vendored.requests.packages.urllib3.connectionpool] Resetting dropped connection: elasticbeanstalk.ap-southeast-2.amazonaws.com
2017-03-23 20:48:57,122 INFO [botocore.vendored.requests.packages.urllib3.connectionpool] Resetting dropped connection: elasticbeanstalk.ap-southeast-2.amazonaws.com
2017-03-23 20:48:57,373 INFO [botocore.vendored.requests.packages.urllib3.connectionpool] Resetting dropped connection: elasticbeanstalk.ap-southeast-2.amazonaws.com
2017-03-23 20:48:57,611 INFO [botocore.vendored.requests.packages.urllib3.connectionpool] Resetting dropped connection: elasticbeanstalk.ap-southeast-2.amazonaws.com
2017-03-23 20:49:04,584 INFO [botocore.vendored.requests.packages.urllib3.connectionpool] Resetting dropped connection: elasticbeanstalk.ap-southeast-2.amazonaws.com
2017-03-23 20:49:04,614 ERROR [ebpreplib.awshelper.AwsHelper] 617e87be-d15f-44ed-bcc6-74fcf54be98f - An error occurred (Throttling) when calling the DescribeEnvironments operation (reached max retries: 4): Rate exceeded
Traceback (most recent call last):
  File "/home/jenkins/jobs/portal_4_systest_deploy/workspace/ebprep-virtualenv/local/lib/python2.7/site-packages/aodn_ebprep-0.9.8-py2.7.egg/ebpreplib/awshelper.py", line 141, in _create_or_update_environment
    IncludeDeleted=False
  File "/home/jenkins/jobs/portal_4_systest_deploy/workspace/ebprep-virtualenv/local/lib/python2.7/site-packages/botocore-1.4.81-py2.7.egg/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/jenkins/jobs/portal_4_systest_deploy/workspace/ebprep-virtualenv/local/lib/python2.7/site-packages/botocore-1.4.81-py2.7.egg/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (Throttling) when calling the DescribeEnvironments operation (reached max retries: 4): Rate exceeded
2017-03-23 20:49:04,617 ERROR [ebpreplib.util] Failed to deploy artifact: An error occurred (Throttling) when calling the DescribeEnvironments operation (reached max retries: 4): Rate exceeded
```
https://jenkins.aodn.org.au/job/portal_4_systest_deploy/99/console

I tried to run the job again, and it was successful

https://jenkins.aodn.org.au/job/portal_4_systest_deploy/100/console

**Comment by lwgordonimos** [comment]
Fixed in https://github.com/aodn/chef-private/pull/2264 by increasing the polling interval
