### ISSUE TITLE
PO Box provision fails trying to remove a talend job

### ISSUE THREAD

**Issue by mhidas** [aodn/chef#774]
I removed a bunch of talend jobs from the PO box node file, then tried to run in up, and I got this:
```
...

==> po:   
==> po: * talend_job[oa_reconstruction-oa_reconstruction] action remove
==> po:     
==> po: 
==> po:     
==> po: ================================================================================
==> po:     
==> po: Error executing action `remove` on resource 'talend_job[oa_reconstruction-oa_reconstruction]'
==> po:     
==> po: ================================================================================
==> po:     
==> po: 
==> po: 
==> po:     
==> po: Chef::Exceptions::ValidationFailed
==> po:     
==> po: ----------------------------------
==> po:     
==> po: Required argument talend_version is missing!
==> po:     
==> po: 
==> po: 
==> po:     
==> po: Cookbook Trace:
==> po:     
==> po: ---------------
==> po:     
==> po: /tmp/vagrant-chef/91e82da9c167cd1386e89859be739799/cookbooks/talend/providers/job.rb:19:in `load_current_resource'
==> po: 
==> po:     
==> po: /tmp/vagrant-chef/aa98cee50b3d66377e8400f004127e2b/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> po: 
==> po:     
==> po: /tmp/vagrant-chef/aa98cee50b3d66377e8400f004127e2b/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> po: 
==> po:     
==> po: /tmp/vagrant-chef/aa98cee50b3d66377e8400f004127e2b/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> po: 
==> po:     /tmp/vagrant-chef/aa98cee50b3d66377e8400f004127e2b/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> po:     /tmp/vagrant-chef/aa98cee50b3d66377e8400f004127e2b/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> po:     
==> po:     Resource Declaration:
==> po:     ---------------------
==> po:     # In /tmp/vagrant-chef/91e82da9c167cd1386e89859be739799/cookbooks/talend/recipes/default.rb
==> po:     
==> po:     142:   talend_job job_id do
==> po:     143:     action      :remove
==> po:     144:     common_name job_id
==> po:     145:     jobs_dir    jobs_dir
==> po:     146:     rubbish_dir rubbish_dir
==> po:     147:   end
==> po:     148: end
==> po:     
==> po:     Compiled Resource:
==> po:     ------------------
==> po:     # Declared in /tmp/vagrant-chef/91e82da9c167cd1386e89859be739799/cookbooks/talend/recipes/default.rb:142:in `block in from_file'
==> po:     
==> po:     talend_job("oa_reconstruction-oa_reconstruction") do
==> po:       action [:remove]
==> po:       retries 0
==> po:       retry_delay 2
==> po:       default_guard_interpreter :default
==> po:       declared_type :talend_job
==> po:       cookbook_name :talend
==> po:       recipe_name "default"
==> po:       common_name "oa_reconstruction-oa_reconstruction"
==> po:       jobs_dir "/usr/local/talend/jobs"
==> po:       rubbish_dir "/usr/local/talend/rubbish"
==> po:     end
==> po:     
==> po: [2019-04-03T11:04:04+11:00] INFO: Running queued delayed notifications before re-raising exception
==> po: [2019-04-03T11:04:04+11:00] INFO: template[/vagrant/src/geoserver/security/usergroup/default/users.xml] sending restart action to service[tomcat_default] (delayed)
==> po: Recipe: imos_webapps::generic_webapp
==> po:   * service[tomcat_default] action restart
==> po: [2019-04-03T11:04:10+11:00] INFO: service[tomcat_default] restarted
==> po: 
==> po:     - restart service service[tomcat_default]
==> po: 
```

**Comment by jonescc** [comment]
So that's related to the changes I made recently to support deployment of talend 7 as well as talend 5 artifacts.   https://github.com/aodn/chef/pull/772

**Comment by jonescc** [comment]
Need to add it to all lwrp actions or make it optional.   I'll have a look.

**Comment by mhidas** [comment]
Not sure if this is relevant, but I also had a similar error when I had a harvester deployed into the PO box from a local artefact and then switched it back to the one from Jenkins.
